name: "sh-checker"
description: "Run shellcheck and/or shfmt on all shell script files and include commentaries, there is a exclude parameter"
author: "luizm"
branding:
  icon: "terminal"
  color: "black"
inputs:
  sh_checker_exclude:
    description: "Directory or file name that doesn't need to be checked"
    required: false
  sh_checker_shfmt_disable:
    description: "If true, it will skip the shfmt. Default is false"
    required: false
  sh_checker_shellcheck_disable:
    description: "If true, it will skip the shellcheck. Default is false"
    required: false
  sh_checker_checkbashisms_enable:
    description: "If true, run checkbashisms tool against scripts. Default is false"
    required: false
    default: "false"
  sh_checker_comment:
    description: "If true, it will show the errors as commentaries in the pull requests. Default is false"
    required: false
  sh_checker_only_diff:
    description: "If true, run only on files changed in the PR branch. Default is false"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
